### PR TITLE
Specify the params file and stack name using environment variables

### PR DESCRIPTION
**Pull request by keyvanm**
*Issue #, if available:* #1

*Description of changes:* Specify the parameters file and stack name using environment variables. They have a default in the Makefile and can be overridden by setting the environment variables `PARAMS_FILE` and `STACK_NAME`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by keyvanm** [comment]
@Till--H Please let me know how to document this in the Readme!

**Comment by Till--H** [comment]
Thanks very much for the PR. My idea for the Readme would be an `Advanced Usage` section in the bottom, describing that those parameters could be overwritten to change parameter file and stack name. But I'm happy to write it as well, if you're short on time.

**Comment by keyvanm** [comment]
No worries, I'll write it.

**Comment by keyvanm** [comment]
Test comment

**Comment by Till--H** [comment]
Thanks for the contribution

**Pull request merged**
